name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "44 21 * * *"
  workflow_dispatch:

jobs:
  sync:
    name: Sync Branch
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    strategy:
      fail-fast: false
      matrix:
        # 定义需要同步的分支对
        include:
          - branch: main
            upstream_branch: main

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Sync with Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: hbq0405/emby-toolkit
          upstream_sync_branch: ${{ matrix.upstream_branch }}
          target_sync_branch: ${{ matrix.branch }}
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          test_mode: false

      - name: Sync Check
        if: failure()
        run: |
          echo "同步失败，可能是上游有强制更新或 Workflow 文件变动，请检查手动 Sync Fork。"