name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 22 * * *"  # 每天运行
  workflow_dispatch:

jobs:
  sync-main:
    name: Sync to main branch
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set Git user identity
        run: |
          git config --global user.name "Waynenet"
          git config --global user.email "54445994+Waynenet@users.noreply.github.com"
          
      - name: Sync to main
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: hbq0405/emby-toolkit
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          test_mode: false

  sync-dev:
    name: Sync to dev branch
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    needs: sync-main  # 等main同步完再同步dev
    
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set Git user identity
        run: |
          git config --global user.name "Waynenet"
          git config --global user.email "54445994+Waynenet@users.noreply.github.com"
          
      - name: Sync to dev
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: hbq0405/emby-toolkit
          upstream_sync_branch: main
          target_sync_branch: dev
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次 "
          exit 1
